"""Top-level ``snakemake`` file that runs analysis."""


import os


configfile: "config.yaml"


# include `dms-vep-pipeline` pipeline Snakemake file
include: os.path.join(config["pipeline_path"], "pipeline.smk")


rule all:
    input:
        variant_count_files,
        rules.check_adequate_variant_counts.output.passed,
        prob_escape_files,
        expand(
            rules.fit_polyclonal.output.pickle,
            antibody_selection_group=antibody_selections["selection_group"].unique(),
        ),
        config["docs"],


# Arbitrary other rules should be added here

# Add any extra data/results files for docs with name: file
extra_data_files = {}


# include `dms-vep-pipeline` docs building Snakemake file
include: os.path.join(config["pipeline_path"], "docs.smk")
