"""Top-level ``snakemake`` file that runs analysis."""


import os


configfile: "config.yaml"


# include `dms-vep-pipeline` pipeline Snakemake file
include: os.path.join(config["pipeline_path"], "pipeline.smk")


rule all:
    input:
        variant_count_files,
        rules.check_adequate_variant_counts.output.passed,
        # antibody escape output
        antibody_escape_files,
        # functional effects of mutations output
        (
            [config["muteffects_observed"], config["muteffects_latent"]]
            if len(func_selections)
            else []
        ),
        # HTML documentation output
        config["docs"],


# Arbitrary other rules should be added here

# Add any extra data/results files for docs with name: file
extra_data_files = {}

# Add any extra HTML documents to display here with name: file
extra_html_docs = {}

# If you add rules with "nb" output that have wildcards, specify the rule name
# and subindex titles for the wildcards as in "docs.smk" for `nb_rule_wildcards`
# and `subindex_titles`
extra_nb_rule_wildcards = {}
extra_subindex_titles = {}


# include `dms-vep-pipeline` docs building Snakemake file
include: os.path.join(config["pipeline_path"], "docs.smk")
