name: dms-vep-pipeline
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - altair=5.0.0
  - biopython=1.81
  - black-jupyter
  - bs4=4.11
  - entrez-direct=16.2
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-nb
  - git-lfs
  - graphviz
  - jupyterlab
  - mafft=7.515
  - mamba
  - markdown=3.4
  - matplotlib=3.6
  - minimap2=2.24
  - nbdime
  - nbstripout
  - nbsphinx=0.8
  - nbsphinx-link=1.3
  - openpyxl
  - pandas=2.0
  - papermill=2.3
  - pip
  - python=3.11
  - snakefmt>=0.8
  - snakemake=7.25
  - sphinx=6.1
  - upsetplot=0.7
  - pip:
    - alignparse==0.6.0
    - dms_variants==1.4.3
    - polyclonal==6.0
