name: dms-vep-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - biopython=1.79
  - jupyterlab
  - mamba
  - minimap2=2.24
  - nbdime
  - nbstripout
  - pandas=1.4
  - papermill=2.3
  - pip
  - python=3.9
  - snakemake=7.3
  - pip:
    - alignparse==0.4.1
    - git+https://github.com/altair-viz/altair@0217b2e73703d3b7b529b73b4dec9c17e7fb09bb
