name: dms-vep-pipeline
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - biopython=1.79  # pinned to 1.79 rather than 1.80 because of this: https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/issues/73
  - black-jupyter
  - bs4=4.11
  - entrez-direct=16.2
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-nb
  - git-lfs
  - graphviz
  - jupyterlab
  - mafft=7.508
  - mamba
  - markdown=3.3
  - matplotlib=3.5
  - minimap2=2.24
  - nbdime
  - nbstripout
  - nbsphinx=0.8
  - nbsphinx-link=1.3
  - openpyxl
  - pandas=1.5
  - papermill=2.3
  - pip
  - python=3.10
  - snakefmt>=0.7
  - snakemake=7.18.2
  - sphinx=4.3  # cannot be updated to 5.3 until this resolved
  - upsetplot=0.6
  - pip:
    - alignparse==0.6.0
    - dms_variants==1.4.2
    - git+https://github.com/altair-viz/altair@0217b2e73703d3b7b529b73b4dec9c17e7fb09bb
    - git+https://github.com/jbloomlab/polyclonal/@3.1
