name: dms-vep-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - biopython=1.79
  - black-jupyter
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-nb
  - git-lfs
  - jupyterlab
  - mamba
  - minimap2=2.24
  - nbdime
  - nbstripout
  - pandas=1.4
  - papermill=2.3
  - pip
  - python=3.9
  - snakefmt
  - snakemake=7.3
  - upsetplot=0.6
  - pip:
    - alignparse==0.4.1
    - dms_variants==1.4.0
    - git+https://github.com/altair-viz/altair@0217b2e73703d3b7b529b73b4dec9c17e7fb09bb
