name: dms-vep-pipeline
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - biopython=1.79
  - black-jupyter
  - entrez-direct=16.2
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-nb
  - git-lfs
  - graphviz
  - jupyterlab
  - mafft=7.505
  - mamba
  - minimap2=2.24
  - nbdime
  - nbstripout
  - nbsphinx=0.8
  - nbsphinx-link=1.3
  - pandas=1.4
  - papermill=2.3
  - pip
  - python=3.9
  - snakefmt
  - snakemake=7.8.1
  - sphinx=4.3
  - upsetplot=0.6
  - pip:
    - alignparse==0.5.0
    - dms_variants==1.4.2
    - git+https://github.com/altair-viz/altair@0217b2e73703d3b7b529b73b4dec9c17e7fb09bb
    - git+https://github.com/jbloomlab/polyclonal/@1.2
