name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: build conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dms-vep-pipeline
          environment-file: environment.yml
          auto-activate-base: false
          auto-update-conda: true
          channel-priority: strict

      - name: lint code with flake8_nb
        # NOTE: must specify the shell so that conda init updates bashrc see:
        #      https://github.com/conda-incubator/setup-miniconda#IMPORTANT
        shell: bash -el {0}
        run: flake8_nb

      - name: check code format with black
        shell: bash -el {0}
        run: black --check .

      - name: check snakemake files format with snakefmt
        shell: bash -el {0}
        run: snakefmt --check .

      - name: lint snakemake files with snakemake --lint
        shell: bash -el {0}
        run: cd test_example && snakemake --lint && cd ..

      - name: run pipeline with default config
        shell: bash -el {0}
        run: rm -rf docs && cd test_example && rm -rf results && snakemake --use-conda -j 2 && cd ..

      - name: run pipeline with no barcode runs
        shell: bash -el {0}
        run: rm -rf docs && cd test_example && rm -rf results && snakemake --use-conda -j 2 --config barcode_runs=null && cd ..

      - name: run pipeline with prebuilt variants
        shell: bash -el {0}
        run: rm -rf docs && cd test_example && rm -rf results && snakemake --use-conda -j 2 --config prebuilt_variants=https://raw.githubusercontent.com/dms-vep/dms-vep-pipeline/main/test_example/results/variants/codon_variants.csv prebuilt_geneseq=https://raw.githubusercontent.com/dms-vep/dms-vep-pipeline/main/test_example/results/gene_sequence/codon.fasta prebuilt_muteffects=https://raw.githubusercontent.com/dms-vep/dms-vep-pipeline/main/test_example/results/muteffects_functional/muteffects_observed.csv && cd ..
